name: gowagr_assessment
description: A Flutter application for the Gowagr Mobile Engineer assessment.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.3

  # Immutable Data & Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Networking
  http: ^1.1.0

  # Local Storage/Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Dependency Injection
  get_it: ^7.6.0
  injectable: ^2.4.1 # ADD THIS

  # Internet Connectivity Check
  internet_connection_checker: ^1.0.0

  # Image Caching
  cached_network_image: ^3.3.0

  # Fonts
  google_fonts: ^6.1.0

  # Date Formatting
  intl: ^0.18.1

  # Others
  phosphor_flutter: ^2.0.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  path_provider: ^2.1.5
  flutter_svg: ^2.0.5
  shimmer: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/png/qalla_app_icon.png"
  min_sdk_android: 21
  icon_size: 36
  # macos:
  #   generate: true
  #   image_path: "assets/images/png/qalla_app_icon.png"
  #   icon_size: 36

flutter_gen:
  integrations:
    flutter_svg: true
    rive: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Code Generation
  build_runner: ^2.4.6
  flutter_launcher_icons: any
  flutter_gen_core: 5.8.0
  flutter_gen: ^5.8.0
  flutter_gen_runner: ^5.8.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  hive_generator: ^2.0.1
  mockito: ^5.4.4
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/svg/
  - assets/images/png/
